version: "3"

services:
  pg_db:
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    depends_on:
      - pg_db
  
  redis:
    image: redis:7.0.4
    restart: always
    command: redis-server ${REDIS_CONF_PATH} --requirepass ${APP_CACHE__PASSWORD}
    ports:
      - ${APP_CACHE__PORT}:${APP_CACHE__PORT}
    volumes:
      - redis_data:/var/lib/redis
      - redis_conf:${REDIS_CONF_PATH}

  redis-insight:
    image: redislabs/redisinsight
    restart: always
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}
    volumes:
      - redis_insight_data:/db

  app:
    build: ./app
    restart: always
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - APP_REPO__TYPE=${APP_REPO__TYPE}
      - APP_REPO__DB_URL=${APP_REPO__DB_URL}
      - APP_PRESENTATION_TYPE=${APP_PRESENTATION_TYPE}
      - APP_API_CACHE_CONTROL__MAX_AGE=${APP_API_CACHE_CONTROL__MAX_AGE}
      - APP_API_ADD_ETAG=${APP_API_ADD_ETAG}
      - APP_CACHE__HOST=${APP_CACHE__HOST}
      - APP_CACHE__PORT=${APP_CACHE__PORT}
      - APP_CACHE__PASSWORD=${APP_CACHE__PASSWORD}
      - APP_CACHE__DB=${APP_CACHE__DB}
      - APP_CACHE__TTL=${APP_CACHE__TTL}
    depends_on:
      - pg_db
    
volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  redis_conf:
  redis_insight_data: