version: "3"

services:
  pg_db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    depends_on:
      - pg_db

  app:
    build: ./app
    restart: always
    ports:
      - 5050:5050
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - APP_REPO__TYPE=${APP_REPO__TYPE}
      - APP_REPO__DB_URL=${APP_REPO__DB_URL}
      - APP_PRESENTATION_TYPE=${APP_PRESENTATION_TYPE}
    depends_on:
      - pg_db
    
volumes:
  postgres_data:
  pgadmin_data: